# Generated by Django 4.2.30 on 2026-08-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_allergen_dietarytag_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('serving_size', models.FloatField(default=100)),
                ('serving_unit', models.CharField(default='g', max_length=30)),
                ('allergens', models.ManyToManyField(blank=True, related_name='foods', to='myapp.allergen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='myapp.foodcategory')),
                ('dietary_tags', models.ManyToManyField(blank=True, related_name='foods', to='myapp.dietarytag')),
            ],
        ),
    ]
