# Generated by Django 4.2.30 on 2026-08-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='food_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meallog',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='myapp.food'),
        ),
    ]
