# Generated by Django 4.2.16 on 2026-09-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_meallog_food_name_alter_meallog_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
