# Generated by Django 4.2.16 on 2026-09-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_meallog_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('serving_size', models.FloatField(default=100)),
                ('serving_unit', models.CharField(default='g', max_length=30)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myapp.food')),
            ],
        ),
    ]
