# Generated by Django 4.2.16 on 2026-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_foodvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
