# Generated by Django 4.2.30 on 2026-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_meallog_carbohydrates_meallog_fat_meallog_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.allergen'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_dietary_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='myapp.dietarytag'),
        ),
    ]
