# Generated by Django 4.2.11 on 2026-09-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_userprofile_allergies_userprofile_custom_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='data_source',
            field=models.CharField(blank=True, default='NepaliNutriDB', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='is_nepali',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_nepali',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('ml_score', models.FloatField(default=0.0)),
                ('budget_fit_score', models.FloatField(default=0.0)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('is_eaten', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_instances', to='myapp.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
    ]
